enum Color {
	Black = "§0",
	DarkBlue = "§1",
	DarkGreen = "§2",
	DarkAqua = "§3",
	DarkRed = "§4",
	DarkPurple = "§5",
	Ochre = "§6",
	Gray = "§7",
	DarkGray = "§8",
	Blue = "§9",
	Green = "§a",
	Aqua = "§b",
	Red = "§c",
	LightPurple = "§d",
	Yellow = "§e",
	White = "§f",
	Minecoin = "§g",
	Quartz = "§h",
	Iron = "§i",
	Netherite = "§j",
	Redstone = "§m",
	Copper = "§n",
	Gold = "§p",
	Emerald = "§q",
	Diamond = "§s",
	Lapis = "§t",
	Amethyst = "§u",
}

export { Color };
